/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.csvandgson;

import org.junit.Test;

import com.bridgelabz.csvandgson.OpenCSVReader;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        OpenCSVReader classUnderTest = new OpenCSVReader();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
